### ISSUE TITLE
Use constants for XML field names in `ServiceResponse.cs`

### ISSUE THREAD

**Issue by guibranco** [guibranco/Sankhya-SDK-dotnet#180]
**Is your feature request related to a problem? Please describe.**
Use constants for XML field names in `ServiceResponse.cs`

**Describe the solution you'd like**
Replace the strings in the class [Src/Sankhya/Service/ServiceResponse.cs](https://github.com/guibranco/Sankhya-SDK-dotnet/blob/main/Src/Sankhya/Service/ServiceResponse.cs) with a constant value from a constant static class to be created.

- Replace strings from XmlAttributes / XmlElement
- Replace strings in `ParseDynamic` method
- Replace strings in `ParseResponseBody` method
- Replace strings in `ParseAttributes` method
- Replace strings in `Process*` methods
- Replace strings in `WriteAttributes` method

**Comment by fandriyaninkov** [comment]
Hi! I searched issue with tag "good first issue" and found your project. Can i create branch and perform this issue?

**Comment by guibranco** [comment]
@fandriyaninkov yes, sure! I will assign it to you!
