### ISSUE TITLE
[FEATURE] Convert class `LowData` to project pattern

### ISSUE THREAD

**Issue by guibranco** [guibranco/Sankhya-SDK-dotnet#21]
**Is your feature request related to a problem? Please describe.**
Convert class `Service.LowData` to the project pattern (SerializationHelpers, Properties, Private fields).

For reference, check the structure/signature of the other classes in the `Service` namespace.
For example: [Key.cs](https://github.com/guibranco/Sankhya-SDK-dotnet/blob/main/Src/Sankhya/Service/Key.cs)

**Comment by guibranco** [comment]
@pedrowindisch if you can comment here, so I can assign this issue to you

**Comment by pedrowindisch** [comment]
Sure, thanks!
