### ISSUE TITLE
[FEATURE] Use `records` for transport classes 

### ISSUE THREAD

**Issue by guibranco** [guibranco/Sankhya-SDK-dotnet#61]
Implement `records` in classes under `Transport` namespace

- [C# 9–Use Record types in .NET Standard 2.0](https://bartwullems.blogspot.com/2021/01/c-9use-record-types-in-net-standard-20.html)
- [Using C#9 record and init property in your .NET Framework 4.x, .NET Standard and .NET Core projects](https://blog.ndepend.com/using-c9-record-and-init-property-in-your-net-framework-4-x-net-standard-and-net-core-projects/)

**Comment by pedrowindisch** [comment]
Hey there, is this still available? If so, I'll try to work on this issue if possible. :)

I'd just like to discuss some design decisions first if you don't mind:

As we're converting those classes into records, I guess it'd be okay to get rid of the `Equals` methods and equality operators overrides, right? (as records are structural equality types/they use value-based equality by default)

And what about the classes that currently inherit from other classes, specifically GenericServiceEntity (such as InvoiceItem)?

**Comment by guibranco** [comment]
Hi @pedrowindisch, I need to investigate this one more thoroughly since I will need to check whether `records` are possible and necessary in this case.

**Comment by pedrowindisch** [comment]
Okay, I'll work on #21 in the meanwhile if you don't mind

**Comment by guibranco** [comment]
Sure, no problem!

**Comment by guibranco** [comment]
Invalid request
